name: app_cuy
description: Cuy app demo for senior app developer
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  user_api:
    path: packages/user_api
  user_api_remote:
    path: packages/user_api_remote
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

  fonts:
    - family: Ubuntu-Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
    - family: Ubuntu-Light
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
